### ISSUE TITLE
Pantalla de inicio

### ISSUE THREAD

**Issue by HumbertoGS** [HumbertoGS/aplicacion-web-tesis#2]
Crear pantalla de inicio, debe tener:

1. - [x] Un subMenu, si es propietario, cliente o quiere registrar datos
2. - [x] Fondo o diseño llamativo

**Comment by FernandaHeLa** [comment]
![image](https://user-images.githubusercontent.com/89749211/210016424-27f87afe-ded8-42b0-99da-9fee10cf79c4.png)

**Comment by FernandaHeLa** [comment]
![image](https://user-images.githubusercontent.com/89749211/212572468-a5e9abd1-4ff8-4dc2-9aa4-4bbfa9e40419.png)
