### ISSUE TITLE
Pantalla registro de compra/venta

### ISSUE THREAD

**Issue by HumbertoGS** [HumbertoGS/aplicacion-web-tesis#3]
Realizar pantalla donde tenga los datos de las ventas en espera del comprobante.
Al tener el número de comprobante del pago realizado, debe registrarse y habilitar el botón para permitir que se registre la venta

Tareas:
- [x] Cuadro de datos de compra/venta
- [x] Cuadro/tabla debe tener campo para número de comprobante, botón de aceptar o rechazar
- [x] campo obligatorio para registrar número de comprobante de pago
- [x] habilitar botón de aprobado al registrar datos de comprobante
- [x] Añadir modal para presentar detalles

**Comment by HumbertoGS** [comment]
![pantalla registro de ventas](https://user-images.githubusercontent.com/81884653/209395416-6e692788-12a9-4cc4-a97a-bbdd00b87e77.png)
Modelo de como mas o menos va

**Comment by HumbertoGS** [comment]
![image](https://user-images.githubusercontent.com/81884653/209414135-102aa672-dbb9-4561-98a0-57e67f270300.png)
Como va quedando

**Comment by HumbertoGS** [comment]
detalles del modal
![image](https://user-images.githubusercontent.com/81884653/209417268-b5d16ee2-64e1-4d5f-be10-ea198369591f.png)

**Comment by FernandaHeLa** [comment]
me parece excelente

**Comment by HumbertoGS** [comment]
![image](https://user-images.githubusercontent.com/81884653/209587363-3988ed77-d2f9-43af-bd96-821e182a1501.png)
modal de advertencia
