### ISSUE TITLE
Pantalla catalogo

### ISSUE THREAD

**Issue by HumbertoGS** [HumbertoGS/aplicacion-web-tesis#5]
Realizar pantalla de catalogo

- [x] Presentar productos
- [x] Agregar filtros por etiqueta ya predefinidas, de tabla catalogo
- [x] Agregar búsqueda por texto (opcional)
- [x] Agregar botón para añadir al carrito
- [x] Presentar en la barra superior de búsqueda, también icono de carrito para dirigir a pantalla de carrito

**Comment by FernandaHeLa** [comment]
![image](https://user-images.githubusercontent.com/89749211/209445234-26ac8391-628d-4ef4-81d4-cf776243ff8c.png)

**Comment by FernandaHeLa** [comment]
aún falta darle vida, pero es la idea

**Comment by FernandaHeLa** [comment]
![image](https://user-images.githubusercontent.com/89749211/209988916-45dde1c5-b15d-4fd1-be1f-628c6190fa86.png)

**Comment by FernandaHeLa** [comment]
![image](https://user-images.githubusercontent.com/89749211/210015791-dfd3f665-fbf4-47ed-b82b-511767ab9e5f.png)
